//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FredroClient.MailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailService.IMailService", CallbackContract=typeof(FredroClient.MailService.IMailServiceCallback))]
    public interface IMailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/Join", ReplyAction="http://tempuri.org/IMailService/JoinResponse")]
        void Join();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/Join", ReplyAction="http://tempuri.org/IMailService/JoinResponse")]
        System.Threading.Tasks.Task JoinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/SendMail", ReplyAction="http://tempuri.org/IMailService/SendMailResponse")]
        void SendMail(FredroDAL.Models.DatabaseObjectModels.Tables.TheMail mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/SendMail", ReplyAction="http://tempuri.org/IMailService/SendMailResponse")]
        System.Threading.Tasks.Task SendMailAsync(FredroDAL.Models.DatabaseObjectModels.Tables.TheMail mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/UpdateMail", ReplyAction="http://tempuri.org/IMailService/UpdateMailResponse")]
        void UpdateMail(FredroDAL.Models.DatabaseObjectModels.Tables.TheMail mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/UpdateMail", ReplyAction="http://tempuri.org/IMailService/UpdateMailResponse")]
        System.Threading.Tasks.Task UpdateMailAsync(FredroDAL.Models.DatabaseObjectModels.Tables.TheMail mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/RemoveMail", ReplyAction="http://tempuri.org/IMailService/RemoveMailResponse")]
        void RemoveMail(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/RemoveMail", ReplyAction="http://tempuri.org/IMailService/RemoveMailResponse")]
        System.Threading.Tasks.Task RemoveMailAsync(string Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/SendNewMails", ReplyAction="http://tempuri.org/IMailService/SendNewMailsResponse")]
        void SendNewMails(FredroDAL.Models.DatabaseObjectModels.Tables.TheMail[] newMails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailServiceChannel : FredroClient.MailService.IMailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServiceClient : System.ServiceModel.DuplexClientBase<FredroClient.MailService.IMailService>, FredroClient.MailService.IMailService {
        
        public MailServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MailServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MailServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Join() {
            base.Channel.Join();
        }
        
        public System.Threading.Tasks.Task JoinAsync() {
            return base.Channel.JoinAsync();
        }
        
        public void SendMail(FredroDAL.Models.DatabaseObjectModels.Tables.TheMail mail) {
            base.Channel.SendMail(mail);
        }
        
        public System.Threading.Tasks.Task SendMailAsync(FredroDAL.Models.DatabaseObjectModels.Tables.TheMail mail) {
            return base.Channel.SendMailAsync(mail);
        }
        
        public void UpdateMail(FredroDAL.Models.DatabaseObjectModels.Tables.TheMail mail) {
            base.Channel.UpdateMail(mail);
        }
        
        public System.Threading.Tasks.Task UpdateMailAsync(FredroDAL.Models.DatabaseObjectModels.Tables.TheMail mail) {
            return base.Channel.UpdateMailAsync(mail);
        }
        
        public void RemoveMail(string Id) {
            base.Channel.RemoveMail(Id);
        }
        
        public System.Threading.Tasks.Task RemoveMailAsync(string Id) {
            return base.Channel.RemoveMailAsync(Id);
        }
    }
}
