//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinklCRM.Client.MailboxService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailboxService.IMailboxService", CallbackContract=typeof(TwinklCRM.Client.MailboxService.IMailboxServiceCallback))]
    public interface IMailboxService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMailboxService/Join")]
        void Join();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMailboxService/Join")]
        System.Threading.Tasks.Task JoinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailboxService/SendMail", ReplyAction="http://tempuri.org/IMailboxService/SendMailResponse")]
        void SendMail(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailboxService/SendMail", ReplyAction="http://tempuri.org/IMailboxService/SendMailResponse")]
        System.Threading.Tasks.Task SendMailAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail mail);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMailboxService/UpdateMail")]
        void UpdateMail(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail mail);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMailboxService/UpdateMail")]
        System.Threading.Tasks.Task UpdateMailAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail mail);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMailboxService/RemoveMail")]
        void RemoveMail(string Id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMailboxService/RemoveMail")]
        System.Threading.Tasks.Task RemoveMailAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailboxService/GetUserEmailBoxes", ReplyAction="http://tempuri.org/IMailboxService/GetUserEmailBoxesResponse")]
        TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.CachedEmailBox[] GetUserEmailBoxes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailboxService/GetUserEmailBoxes", ReplyAction="http://tempuri.org/IMailboxService/GetUserEmailBoxesResponse")]
        System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.CachedEmailBox[]> GetUserEmailBoxesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailboxServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMailboxService/SendNewInboxMails")]
        void SendNewInboxMails(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail[] newMails);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMailboxService/SendNewOutboxMails")]
        void SendNewOutboxMails(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail[] newMails);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMailboxService/SendNewSpamMails")]
        void SendNewSpamMails(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail[] newMails);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMailboxService/SendNewDeletedMails")]
        void SendNewDeletedMails(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail[] newMails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailboxServiceChannel : TwinklCRM.Client.MailboxService.IMailboxService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailboxServiceClient : System.ServiceModel.DuplexClientBase<TwinklCRM.Client.MailboxService.IMailboxService>, TwinklCRM.Client.MailboxService.IMailboxService {
        
        public MailboxServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MailboxServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MailboxServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MailboxServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MailboxServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Join() {
            base.Channel.Join();
        }
        
        public System.Threading.Tasks.Task JoinAsync() {
            return base.Channel.JoinAsync();
        }
        
        public void SendMail(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail mail) {
            base.Channel.SendMail(mail);
        }
        
        public System.Threading.Tasks.Task SendMailAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail mail) {
            return base.Channel.SendMailAsync(mail);
        }
        
        public void UpdateMail(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail mail) {
            base.Channel.UpdateMail(mail);
        }
        
        public System.Threading.Tasks.Task UpdateMailAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.TheMail mail) {
            return base.Channel.UpdateMailAsync(mail);
        }
        
        public void RemoveMail(string Id) {
            base.Channel.RemoveMail(Id);
        }
        
        public System.Threading.Tasks.Task RemoveMailAsync(string Id) {
            return base.Channel.RemoveMailAsync(Id);
        }
        
        public TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.CachedEmailBox[] GetUserEmailBoxes() {
            return base.Channel.GetUserEmailBoxes();
        }
        
        public System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.CachedEmailBox[]> GetUserEmailBoxesAsync() {
            return base.Channel.GetUserEmailBoxesAsync();
        }
    }
}
