//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinklCRM.Client.BusinessObjectService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusinessObjectService.IBusinessObjectService")]
    public interface IBusinessObjectService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetPerformer", ReplyAction="http://tempuri.org/IBusinessObjectService/GetPerformerResponse")]
        TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer GetPerformer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetPerformer", ReplyAction="http://tempuri.org/IBusinessObjectService/GetPerformerResponse")]
        System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer> GetPerformerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/DeletePerformer", ReplyAction="http://tempuri.org/IBusinessObjectService/DeletePerformerResponse")]
        void DeletePerformer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/DeletePerformer", ReplyAction="http://tempuri.org/IBusinessObjectService/DeletePerformerResponse")]
        System.Threading.Tasks.Task DeletePerformerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/UpdatePerformer", ReplyAction="http://tempuri.org/IBusinessObjectService/UpdatePerformerResponse")]
        void UpdatePerformer(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer performer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/UpdatePerformer", ReplyAction="http://tempuri.org/IBusinessObjectService/UpdatePerformerResponse")]
        System.Threading.Tasks.Task UpdatePerformerAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer performer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/InsertPerformer", ReplyAction="http://tempuri.org/IBusinessObjectService/InsertPerformerResponse")]
        void InsertPerformer(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer performer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/InsertPerformer", ReplyAction="http://tempuri.org/IBusinessObjectService/InsertPerformerResponse")]
        System.Threading.Tasks.Task InsertPerformerAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer performer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetDeal", ReplyAction="http://tempuri.org/IBusinessObjectService/GetDealResponse")]
        TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal GetDeal(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetDeal", ReplyAction="http://tempuri.org/IBusinessObjectService/GetDealResponse")]
        System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal> GetDealAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/DeleteDeal", ReplyAction="http://tempuri.org/IBusinessObjectService/DeleteDealResponse")]
        void DeleteDeal(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/DeleteDeal", ReplyAction="http://tempuri.org/IBusinessObjectService/DeleteDealResponse")]
        System.Threading.Tasks.Task DeleteDealAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/UpdateDeal", ReplyAction="http://tempuri.org/IBusinessObjectService/UpdateDealResponse")]
        void UpdateDeal(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/UpdateDeal", ReplyAction="http://tempuri.org/IBusinessObjectService/UpdateDealResponse")]
        System.Threading.Tasks.Task UpdateDealAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/InsertDeal", ReplyAction="http://tempuri.org/IBusinessObjectService/InsertDealResponse")]
        void InsertDeal(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/InsertDeal", ReplyAction="http://tempuri.org/IBusinessObjectService/InsertDealResponse")]
        System.Threading.Tasks.Task InsertDealAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetCustomer", ReplyAction="http://tempuri.org/IBusinessObjectService/GetCustomerResponse")]
        TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer GetCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetCustomer", ReplyAction="http://tempuri.org/IBusinessObjectService/GetCustomerResponse")]
        System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer> GetCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/DeleteCustomer", ReplyAction="http://tempuri.org/IBusinessObjectService/DeleteCustomerResponse")]
        void DeleteCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/DeleteCustomer", ReplyAction="http://tempuri.org/IBusinessObjectService/DeleteCustomerResponse")]
        System.Threading.Tasks.Task DeleteCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/UpdateCustomer", ReplyAction="http://tempuri.org/IBusinessObjectService/UpdateCustomerResponse")]
        void UpdateCustomer(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/UpdateCustomer", ReplyAction="http://tempuri.org/IBusinessObjectService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task UpdateCustomerAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/InsertCustomer", ReplyAction="http://tempuri.org/IBusinessObjectService/InsertCustomerResponse")]
        void InsertCustomer(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/InsertCustomer", ReplyAction="http://tempuri.org/IBusinessObjectService/InsertCustomerResponse")]
        System.Threading.Tasks.Task InsertCustomerAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetAllCustomers", ReplyAction="http://tempuri.org/IBusinessObjectService/GetAllCustomersResponse")]
        TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer[] GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetAllCustomers", ReplyAction="http://tempuri.org/IBusinessObjectService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer[]> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetAllPerformers", ReplyAction="http://tempuri.org/IBusinessObjectService/GetAllPerformersResponse")]
        TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer[] GetAllPerformers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetAllPerformers", ReplyAction="http://tempuri.org/IBusinessObjectService/GetAllPerformersResponse")]
        System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer[]> GetAllPerformersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetAllVehicles", ReplyAction="http://tempuri.org/IBusinessObjectService/GetAllVehiclesResponse")]
        TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Vehicle[] GetAllVehicles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetAllVehicles", ReplyAction="http://tempuri.org/IBusinessObjectService/GetAllVehiclesResponse")]
        System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Vehicle[]> GetAllVehiclesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetAllTripTypes", ReplyAction="http://tempuri.org/IBusinessObjectService/GetAllTripTypesResponse")]
        TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Dictionaries.DictionaryTripType[] GetAllTripTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessObjectService/GetAllTripTypes", ReplyAction="http://tempuri.org/IBusinessObjectService/GetAllTripTypesResponse")]
        System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Dictionaries.DictionaryTripType[]> GetAllTripTypesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusinessObjectServiceChannel : TwinklCRM.Client.BusinessObjectService.IBusinessObjectService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessObjectServiceClient : System.ServiceModel.ClientBase<TwinklCRM.Client.BusinessObjectService.IBusinessObjectService>, TwinklCRM.Client.BusinessObjectService.IBusinessObjectService {
        
        public BusinessObjectServiceClient() {
        }
        
        public BusinessObjectServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessObjectServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessObjectServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessObjectServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer GetPerformer(int id) {
            return base.Channel.GetPerformer(id);
        }
        
        public System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer> GetPerformerAsync(int id) {
            return base.Channel.GetPerformerAsync(id);
        }
        
        public void DeletePerformer(int id) {
            base.Channel.DeletePerformer(id);
        }
        
        public System.Threading.Tasks.Task DeletePerformerAsync(int id) {
            return base.Channel.DeletePerformerAsync(id);
        }
        
        public void UpdatePerformer(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer performer) {
            base.Channel.UpdatePerformer(performer);
        }
        
        public System.Threading.Tasks.Task UpdatePerformerAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer performer) {
            return base.Channel.UpdatePerformerAsync(performer);
        }
        
        public void InsertPerformer(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer performer) {
            base.Channel.InsertPerformer(performer);
        }
        
        public System.Threading.Tasks.Task InsertPerformerAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer performer) {
            return base.Channel.InsertPerformerAsync(performer);
        }
        
        public TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal GetDeal(int id) {
            return base.Channel.GetDeal(id);
        }
        
        public System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal> GetDealAsync(int id) {
            return base.Channel.GetDealAsync(id);
        }
        
        public void DeleteDeal(int id) {
            base.Channel.DeleteDeal(id);
        }
        
        public System.Threading.Tasks.Task DeleteDealAsync(int id) {
            return base.Channel.DeleteDealAsync(id);
        }
        
        public void UpdateDeal(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal deal) {
            base.Channel.UpdateDeal(deal);
        }
        
        public System.Threading.Tasks.Task UpdateDealAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal deal) {
            return base.Channel.UpdateDealAsync(deal);
        }
        
        public void InsertDeal(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal deal) {
            base.Channel.InsertDeal(deal);
        }
        
        public System.Threading.Tasks.Task InsertDealAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Deal deal) {
            return base.Channel.InsertDealAsync(deal);
        }
        
        public TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer GetCustomer(int id) {
            return base.Channel.GetCustomer(id);
        }
        
        public System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer> GetCustomerAsync(int id) {
            return base.Channel.GetCustomerAsync(id);
        }
        
        public void DeleteCustomer(int id) {
            base.Channel.DeleteCustomer(id);
        }
        
        public System.Threading.Tasks.Task DeleteCustomerAsync(int id) {
            return base.Channel.DeleteCustomerAsync(id);
        }
        
        public void UpdateCustomer(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer customer) {
            base.Channel.UpdateCustomer(customer);
        }
        
        public System.Threading.Tasks.Task UpdateCustomerAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer customer) {
            return base.Channel.UpdateCustomerAsync(customer);
        }
        
        public void InsertCustomer(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer customer) {
            base.Channel.InsertCustomer(customer);
        }
        
        public System.Threading.Tasks.Task InsertCustomerAsync(TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer customer) {
            return base.Channel.InsertCustomerAsync(customer);
        }
        
        public TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer[] GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Customer[]> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer[] GetAllPerformers() {
            return base.Channel.GetAllPerformers();
        }
        
        public System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Performer[]> GetAllPerformersAsync() {
            return base.Channel.GetAllPerformersAsync();
        }
        
        public TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Vehicle[] GetAllVehicles() {
            return base.Channel.GetAllVehicles();
        }
        
        public System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Vehicle[]> GetAllVehiclesAsync() {
            return base.Channel.GetAllVehiclesAsync();
        }
        
        public TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Dictionaries.DictionaryTripType[] GetAllTripTypes() {
            return base.Channel.GetAllTripTypes();
        }
        
        public System.Threading.Tasks.Task<TwinklCRM.DAL.Models.DatabaseObjectModels.Tables.Dictionaries.DictionaryTripType[]> GetAllTripTypesAsync() {
            return base.Channel.GetAllTripTypesAsync();
        }
    }
}
